---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "checklist.fullname" . }}-admin-service
  labels:
    app: {{ include "checklist.name" . }}-admin
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    app: {{ include "checklist.name" . }}-admin
  ports:
  - name: http-port
    port: {{ .Values.admin.service.port }}
    protocol: TCP
    targetPort: {{ .Values.admin.service.targetPort }}